teacher_model:
  name: "syvai/hviske-v2"
  device: 1
  fp16: false

student_model:
  name: "openai/whisper-large-v3-turbo"
  device: 1
  fp16: false

dataset:
  name: "alexandrainst/coral"
  data_dir: "huge_subset/data"
  train_split: "train"
  eval_split: "val"
  config: da
  train_size: 25000
  val_size: 500
  num_proc: 5
  seed: 42

training:
  output_dir: "models/distilled-whisper-turbo-large_subset"
  per_device_train_batch_size: 24
  per_device_eval_batch_size: 24
  eval_accumulation_steps: 10
  gradient_accumulation_steps: 1
  learning_rate: 3e-5
  num_train_epochs: 1
  train_samples: 250
  val_samples: 10
  dataloader_workers: 4
  fp16: false
  bf16: true
  logging_steps: 1000
  temperature: 2
  alpha: 0.6
  warmup_steps: 500
  warmup_ratio: 0.1

lora:
  rank: 16
  alpha: 64
  dropout: 0.05
  target_modules: [
    "q_proj", 
    "v_proj",
    "k_proj",
    "out_proj",
    "fc1",
    "fc2"
  ]