baseline_model:
  name: "syvai/hviske-v2"
  dataset_name: "google/fleurs"
  dataset_config: "da_dk"
  label_column: "transcription"
  batch_size: 8
  device: 0
  max_test_samples: null

finetuning:
  learning_rate: 2e-5
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01

pruning:
  method: "magnitude"
  amount: 0.3
  schedule: "gradual" 