model:
  path: "C:/Users/jbhan/Desktop/Deep/models/whisper-large-v3-turbo-finetuned_large_subset"
  # path: "syvai/hviske-v2"
  device: 0  # Use GPU 0
  fp16: true

dataset:
  name: "alexandrainst/coral"
  config: null
  split: "test"
  batch_size: 16