model:
  # path: "openai/whisper-large-v3-turbo"
  path: "/home/shadeform/DeepLearning_ExamProject/models/distilled-whisper-turbo-latest"
  device: 0  # Use GPU 0
  fp16: false

dataset:
  name: "alexandrainst/coral"
  config: null
  split: "test"
  batch_size: 32