model:
  path: "/home/shadeform/DeepLearning_ExamProject/models/distilled-whisper-turbo-large_subset"
  # path: "syvai/hviske-v2"
  device: 0  # Use GPU 0
  fp16: false

dataset:
  name: "alexandrainst/coral"
  config: null
  split: "test"
  batch_size: 64