defaults:
  - _self_

# Training parameters
training:
  output_dir: "models/whisper-large-v3-turbo"
  num_train_epochs: 1
  batch_size: 16
  gradient_accumulation_steps: 2
  learning_rate: 1e-5
  weight_decay: 0.01
  warmup_steps: 100
  max_steps: -1
  fp16: true
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 1000

# Model parameters
model:
  name: "openai/whisper-large-v3-turbo"
  freeze_encoder: true

# Dataset parameters
dataset:
  name: "alexandrainst/coral"
  config: null
  sampling_rate: 16000
  num_proc: 1
  train_split: "train"
  eval_split: "test"
  train_size: 500
  val_size: 100