defaults:
  - _self_

# Training parameters
training:
  output_dir: "models/whisper-large-v3-turbo"
  num_train_epochs: 3
  batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 1e-5
  weight_decay: 0.01
  warmup_steps: 500
  max_steps: -1
  fp16: false
  bf16: True
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 1000

# Model parameters
model:
  name: "openai/whisper-large-v3"
  device: 0
  fp16: false

# Dataset parameters
dataset:
  name: "alexandrainst/coral"
  config: null
  sampling_rate: 16000
  num_proc: 30
  batch_size_per_proc: 8
  train_split: "train"
  eval_split: "val"
  train_size: 5000
  val_size: 500
  seed: 42